### ISSUE TITLE
cadastrarRepasseFinanceiro

### ISSUE THREAD

**Issue by laoliveira** [laoliveira/UNIFunda#14]
Botão de "Voltar" está incorreto, leva para listagem de usuários e dá erro. (deveria voltar para relação de projetos aprovados?) @danielpfernandes

**Comment by laoliveira** [comment]
Não está dando erro com a versão mais nova do DB, ainda assim volta para página incorreta.

**Comment by danielpfernandes** [comment]
Corrigido com o commit 2f03b54
