### ISSUE TITLE
removerProjetoCandidato

### ISSUE THREAD

**Issue by laoliveira** [laoliveira/UNIFunda#3]
Remoção deleta do banco de dados, atualizar de forma que apenas marque uma flag de conta desativada, não remover totalmente do sistema.

**Comment by danielpfernandes** [comment]
Verificar os arquivos crudUsuario.php e desativarUsuario.php para possível solução. Será preciso criar uma coluna para registrar o flag.

**Comment by laoliveira** [comment]
resolvidoresolvido no commit #[https://github.com/laoliveira/UNIFunda/commit/3857185519aaa027dbb554087643afcf684427d4](url)
