### ISSUE TITLE
criarUsuario - Categoria

### ISSUE THREAD

**Issue by laoliveira** [laoliveira/UNIFunda#5]
Não existe o campo categoria na criação de usuário.

**Comment by laoliveira** [comment]
Resolvido na Branch RemakeLaravel.

**Comment by laoliveira** [comment]
Branch de correcao descontinuada, problema ainda existente na master.

**Comment by danielpfernandes** [comment]
Parcialmente resolvido. Falta alterar os valores das entradas no dropdown box

**Comment by danielpfernandes** [comment]
Arrumado com o commit "Update cadastrarUsuario.php"
